services:
  todo.app:
    build: .
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=TodoDb;User=sa;Password=ahojAhoj12@3;TrustServerCertificate=True;
    depends_on:
      - db
    ports:
      - "5000:8080"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ahojAhoj12@3"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
